repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        types: [python]
        language: system
        pass_filenames: false

      - id: isort
        name: isort
        entry: isort .
        types: [python]
        language: system
        pass_filenames: false