name: tests

on:
  - push
  - pull_request

jobs:
  build:
    name: clorm ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install prerequisites
      shell: pwsh
      run: |
        pip install -r requirements.txt

    - name: install clorm
      shell: pwsh
      run: |
        python setup.py install

    - name: info
      shell: pwsh
      run: |
        python -VV
        pip list

    - name: test
      shell: pwsh
      run: |
        python -m unittest tests
